// 此模块只翻译 ChangeFleet 自己定义的诊断；Git 和测试程序的原始输出必须保留为证据，不能擅自改写。
export const DEFAULT_LOCALE = "zh-CN";

const MESSAGES = {
  "zh-CN": {
    INVALID_CLI_INVOCATION: "本地 ChangeFleet 命令参数无效。",
    INVALID_CLI_CONFIG: "本地 ChangeFleet 配置无效。",
    INVALID_CLI_REQUEST: "本地 ChangeFleet 请求无效。",
    INVALID_OPERATOR_APPLICATION: "ChangeFleet 操作应用装配无效。",
    INVALID_OPERATOR_REQUEST: "ChangeFleet 操作请求必须是 JSON 对象。",
    UNSUPPORTED_OPERATOR_OPERATION: "请求的 ChangeFleet 操作未被允许。",
    UNSUPPORTED_CLI_RUNTIME: "本地命令选择了不支持的 Runtime。",
    CODEX_CREDENTIALS_UNAVAILABLE: "所选 Codex 凭据不可用。",
    CLI_COMMAND_FAILED: "无法完成本地 ChangeFleet 命令。",
    INVALID_AUDIT_INVOCATION: "本地审计命令参数无效。",
    AUDIT_COMMAND_FAILED: "无法完成本地审计查询。",
    INVALID_AUDIT_QUERY: "审计查询参数无效。",
    AUDIT_SOURCE_NOT_FOUND: "未找到请求的审计源。",
    AUDIT_REQUIRED_REFERENCE_INVALID: "审计所需的不可变引用无效或缺失。",
    AUDIT_SOURCE_IDENTITY_MISMATCH: "审计源身份或内容摘要不匹配。",
    AMBIGUOUS_OBSERVATION_OVERLAP: "用量观察可能重叠，无法安全计算唯一总量。",
    INVALID_ID: "标识符格式无效。",
    INVALID_PLAN: "变更计划无效。",
    INVALID_REVISION_FEEDBACK: "修订反馈缺失、重复或超出允许范围。",
    INVALID_CANDIDATE_CHECKPOINT: "候选检查点身份无效。",
    INVALID_VALIDATION_ATTEMPT: "验证尝试记录无效。",
    INVALID_PROJECT_REPOSITORIES: "项目必须显式登记至少一个仓库。",
    INVALID_REPOSITORY_SELECTION: "仓库选择无效。",
    INVALID_REPOSITORY_SELECTION_REVISION: "仓库选择版本无效。",
    INVALID_REPOSITORY_HARNESS_POLICY: "仓库 Harness 策略无效。",
    INVALID_REPOSITORY_HARNESS_SELECTION: "仓库 Harness 选择无效。",
    INVALID_REPOSITORY_HARNESS_SELECTION_REVISION: "仓库 Harness 选择版本无效。",
    STALE_REPOSITORY_HARNESS_SELECTION_REVISION: "待修订的仓库 Harness 选择已不是当前版本。",
    REPOSITORY_HARNESS_POLICY_REQUIRED: "启用本地 Harness overlay 前必须确认仓库策略。",
    REPOSITORY_HARNESS_POLICY_NOT_FOUND: "未找到指定的仓库 Harness 策略版本。",
    WORKTREEINCLUDE_NOT_TRACKED_AT_BASE: "所选基线没有受 Git 管理的 .worktreeinclude。",
    UNSAFE_HARNESS_PATH: "Harness 路径超出了允许的仓库边界。",
    UNSUPPORTED_HARNESS_RESOURCE: "所选文件不是允许的 Provider 语义 Harness 资源。",
    EMPTY_HARNESS_OVERLAY: "仓库 Harness 策略没有匹配到可用的忽略文件。",
    HARNESS_OVERLAY_LIMIT_EXCEEDED: "仓库 Harness overlay 超出了文件或字节限制。",
    HARNESS_OVERLAY_MODIFIED: "运行过程修改了冻结的 Harness overlay。",
    NON_GIT_HARNESS_CHANGE_UNSUPPORTED: "ChangeFleet 不支持交付未由 Git 管理的 Harness 修改。",
    REPOSITORY_NOT_REGISTERED: "所选仓库未登记在当前项目中。",
    REPOSITORY_NOT_PLANNING_VISIBLE: "仓库不在当前规划可见范围内。",
    REPOSITORY_BRANCH_SELECTION_REQUIRED: "检出点不在分支上，必须显式选择仓库分支。",
    INVALID_BRANCH_REF: "只能选择有效的本地分支作为基线。",
    INVALID_TARGET_REF: "只能选择有效的本地分支作为目标。",
    STALE_REPOSITORY_SELECTION_REVISION: "待修订的仓库选择已不是当前版本。",
    INVALID_REPOSITORY_SELECTION_CHANGE_REQUEST: "Agent 返回的仓库选择变更请求无效。",
    SCOPE_EXPANSION_REQUIRED: "计划请求了尚未授权的仓库范围，需要人工确认。",
    INCOMPLETE_REPOSITORY_SCOPE: "计划必须至少包含一个仓库工作单元。",
    DUPLICATE_WORK_UNIT: "计划中存在重复的工作单元标识符。",
    DUPLICATE_STRING: "列表中存在重复文本。",
    DUPLICATE_REPOSITORY_WORK_UNIT: "同一仓库在一个计划中只能有一个工作单元。",
    MISSING_FROZEN_BASE: "仓库没有可执行的冻结基线版本。",
    WORK_UNIT_DEPENDENCY_CYCLE: "工作单元依赖关系存在循环。",
    UNKNOWN_WORK_UNIT_DEPENDENCY: "工作单元依赖了不存在的工作单元。",
    COMBINED_VALIDATION_FAILED: "候选集合的联合验证未通过。",
    INITIAL_CONTEXT_BUDGET_EXCEEDED: "初始上下文超过允许的 70% 预算。",
    PROJECT_NOT_FOUND: "未找到指定项目。",
    CHANGE_SET_NOT_FOUND: "未找到指定变更单。",
    PLAN_CONFIRMATION_REQUIRED: "计划尚未经过人工确认，不能执行。",
    STALE_PLAN_CONFIRMATION: "待确认的计划已不是当前版本。",
    STALE_BUNDLE_DECISION: "待审核的候选包已不是当前精确版本。",
    INVALID_CHANGE_SET_STATE: "当前变更单状态不允许此操作。",
    INVALID_CHANGE_SET_CLOSURE: "变更单关闭请求缺失、包含未知字段或超出允许范围。",
    CHANGE_SET_ABANDONED: "变更单已经关闭，不能再执行生命周期变更。",
    CHANGE_SET_NOT_QUIESCENT: "变更单仍有运行或命令正在执行，当前不能关闭。",
    CHANGE_SET_DELIVERY_STARTED: "变更单已经开始交付，当前不能关闭。",
    CHANGE_SET_ALREADY_TERMINAL: "变更单已经处于终态，不能再次关闭。",
    INCOMPLETE_CANDIDATE_SET: "候选结果尚未覆盖当前计划的全部工作单元。",
    MISSING_REQUIRED_EVIDENCE: "缺少生成候选包所需的不可变证据。",
    REPOSITORY_VALIDATION_FAILED: "仓库候选结果未通过验证。",
    RUNTIME_IMPLEMENTATION_BLOCKED: "Agent Runtime 未能完成当前实现。",
    EMPTY_IMPLEMENTATION_RESULT: "Agent Runtime 没有产生可交付的 Git 修改。",
    EXECUTION_RETRY_SUBJECT_MISMATCH: "待重试工作区与当前精确工作单元不一致。",
    EXECUTION_RETRY_HEAD_MOVED: "待重试工作区的 Git HEAD 已离开确认基线。",
    EXECUTION_RETRY_WORKSPACE_DIRTY: "待重试工作区包含部分修改，不能自动重置。",
    COMMAND_SPAWN_FAILED: "无法启动验证命令。",
    CANDIDATE_CHECKPOINT_NOT_RESUMABLE: "候选检查点当前不可恢复验证。",
    CANDIDATE_CHECKPOINT_SUBJECT_MISMATCH: "候选检查点与当前精确工作单元不一致。",
    CANDIDATE_CHECKPOINT_RUN_MISMATCH: "候选检查点的来源运行不一致。",
    CANDIDATE_CHECKPOINT_STATE_MISMATCH: "候选检查点持久化状态不一致。",
    LEGACY_RECOVERY_SUBJECT_MISMATCH: "旧记录恢复主体与当前精确工作单元不一致。",
    LEGACY_RECOVERY_RUN_MISMATCH: "旧记录恢复来源运行不一致。",
    STALE_PLAN_REVISION: "指定计划已不是当前确认版本。",
    IDEMPOTENCY_KEY_REUSED: "同一个幂等键不能用于不同输入。",
    LOCK_BUSY: "控制面当前被另一个执行者占用。",
    NOT_A_GIT_REPOSITORY: "指定路径不是 Git 仓库。",
    DIRTY_CANDIDATE_WORKSPACE: "候选工作区含有未提交修改。",
    CANDIDATE_HEAD_MISMATCH: "候选工作区的 Git 提交与记录不一致。",
    CANDIDATE_REPOSITORY_MISMATCH: "候选结果不属于指定仓库。",
    CANDIDATE_CHANGED_PATHS_MISMATCH: "候选结果的变更路径与 Git 主体不一致。",
    INVALID_GITHUB_DELIVERY_BINDING: "GitHub 交付绑定无效。",
    GITHUB_DELIVERY_BINDING_REQUIRED: "仓库尚未确认 GitHub 交付绑定。",
    GITHUB_DELIVERY_BINDING_NOT_FOUND: "未找到指定的 GitHub 交付绑定版本。",
    GITHUB_REMOTE_IDENTITY_MISMATCH: "Git 远端与确认的 GitHub 仓库不一致。",
    UNSUPPORTED_GITHUB_REMOTE: "Git 远端不是受支持的 GitHub 地址。",
    INVALID_DELIVERY_REQUEST: "交付请求身份无效。",
    DELIVERY_CANDIDATE_NOT_IN_BUNDLE: "交付候选不属于已接受的候选包。",
    DELIVERY_CANDIDATE_NOT_FOUND: "找不到交付所绑定的精确候选。",
    DELIVERY_EMPTY_CANDIDATE_UNSUPPORTED: "无变更候选不能创建 GitHub 拉取请求。",
    BUNDLE_ACCEPTANCE_REQUIRED: "当前精确候选包尚未被接受，不能交付。",
    DELIVERY_NOT_PUBLISHED: "当前候选包尚未建立完整交付请求。",
    DELIVERY_TARGET_MOVED: "交付目标已从候选基线移动。",
    DELIVERY_BRANCH_DIVERGED: "交付分支已指向不同提交。",
    DELIVERY_RESULT_UNVERIFIED: "无法验证 GitHub 的精确合入结果。",
    INVALID_GITHUB_PULL_REQUEST: "GitHub 拉取请求响应无效。",
    INVALID_GITHUB_PULL_REQUEST_TEXT: "GitHub 拉取请求文本无效。",
    INVALID_GITHUB_RESPONSE: "GitHub 返回了无效响应。",
    AMBIGUOUS_GITHUB_PULL_REQUEST: "同一交付分支匹配了多个 GitHub 拉取请求。",
    GITHUB_PULL_REQUEST_NOT_FOUND: "未找到预期的 GitHub 拉取请求。",
    GITHUB_COMMAND_FAILED: "GitHub 命令执行失败。",
    DELIVERY_GIT_PUSH_FAILED: "无法发布精确候选到 Git 远端。",
    GIT_REMOTE_READ_FAILED: "无法读取 Git 远端目标。",
    INVALID_DELIVERY_STATE: "交付状态无效。",
    INVALID_DELIVERY_TARGET_REF: "交付目标必须是分支引用。",
    INVALID_DELIVERY_BRANCH: "ChangeFleet 交付分支名称无效。",
    INVALID_COMMIT_SHA: "Git 提交标识无效。",
    AMBIGUOUS_GIT_REMOTE_REF: "Git 远端返回了不唯一的目标引用。",
    INVALID_GIT_REMOTE_RESPONSE: "Git 远端返回了无效引用。",
    GIT_DELIVERY_COMMAND_FAILED: "无法执行 Git 交付命令。",
    GIT_COMMIT_NOT_FOUND: "找不到指定的 Git 提交。",
    DELIVERY_RESULT_VERIFICATION_FAILED: "无法对 Git 目标验证交付结果。",
    DELIVERY_BUNDLE_NOT_FOUND: "找不到交付所绑定的候选包。",
    DELIVERY_REQUEST_NOT_FOUND: "找不到指定的交付请求。",
    COMMAND_PREVIOUSLY_FAILED: "相同幂等命令此前已经失败。",
    COMMAND_STATE_MISMATCH: "持久化命令状态与当前操作不一致。",
  },
  en: {
    INVALID_CLI_INVOCATION: "Local ChangeFleet command arguments are invalid.",
    INVALID_CLI_CONFIG: "Local ChangeFleet configuration is invalid.",
    INVALID_CLI_REQUEST: "Local ChangeFleet request is invalid.",
    INVALID_OPERATOR_APPLICATION: "The ChangeFleet operator application is invalid.",
    INVALID_OPERATOR_REQUEST: "The ChangeFleet operator request must be a JSON object.",
    UNSUPPORTED_OPERATOR_OPERATION: "The requested ChangeFleet operation is not allowed.",
    UNSUPPORTED_CLI_RUNTIME: "The local command selected an unsupported Runtime.",
    CODEX_CREDENTIALS_UNAVAILABLE: "The selected Codex credentials are unavailable.",
    CLI_COMMAND_FAILED: "The local ChangeFleet command could not be completed.",
    INVALID_AUDIT_INVOCATION: "Local audit command arguments are invalid.",
    AUDIT_COMMAND_FAILED: "The local audit query could not be completed.",
    INVALID_AUDIT_QUERY: "Audit query parameters are invalid.",
    AUDIT_SOURCE_NOT_FOUND: "The requested audit source was not found.",
    AUDIT_REQUIRED_REFERENCE_INVALID: "A required immutable audit reference is missing or invalid.",
    AUDIT_SOURCE_IDENTITY_MISMATCH: "Audit source identity or content digest does not match.",
    AMBIGUOUS_OBSERVATION_OVERLAP: "Usage observations may overlap, so one safe total cannot be derived.",
    INVALID_ID: "Identifier format is invalid.",
    INVALID_PLAN: "Change plan is invalid.",
    INVALID_REVISION_FEEDBACK: "Revision feedback is missing, duplicated, or outside its bounds.",
    INVALID_CANDIDATE_CHECKPOINT: "CandidateCheckpoint identity is invalid.",
    INVALID_VALIDATION_ATTEMPT: "Validation attempt record is invalid.",
    INVALID_PROJECT_REPOSITORIES: "A Project must explicitly register at least one Repository.",
    INVALID_REPOSITORY_SELECTION: "Repository selection is invalid.",
    INVALID_REPOSITORY_SELECTION_REVISION: "Repository selection revision is invalid.",
    INVALID_REPOSITORY_HARNESS_POLICY: "Repository Harness policy is invalid.",
    INVALID_REPOSITORY_HARNESS_SELECTION: "Repository Harness selection is invalid.",
    INVALID_REPOSITORY_HARNESS_SELECTION_REVISION: "Repository Harness selection revision is invalid.",
    STALE_REPOSITORY_HARNESS_SELECTION_REVISION: "The Repository Harness selection being revised is no longer current.",
    REPOSITORY_HARNESS_POLICY_REQUIRED: "A confirmed Repository policy is required before enabling a local Harness overlay.",
    REPOSITORY_HARNESS_POLICY_NOT_FOUND: "The requested Repository Harness policy revision was not found.",
    WORKTREEINCLUDE_NOT_TRACKED_AT_BASE: "The selected base has no tracked .worktreeinclude.",
    UNSAFE_HARNESS_PATH: "The Harness path exceeds the authorized Repository boundary.",
    UNSUPPORTED_HARNESS_RESOURCE: "The selected file is not an eligible Provider semantic Harness resource.",
    EMPTY_HARNESS_OVERLAY: "The Repository Harness policy matched no eligible ignored files.",
    HARNESS_OVERLAY_LIMIT_EXCEEDED: "The Repository Harness overlay exceeds its file or byte limits.",
    HARNESS_OVERLAY_MODIFIED: "The Run modified the frozen Harness overlay.",
    NON_GIT_HARNESS_CHANGE_UNSUPPORTED: "ChangeFleet cannot deliver a Harness change that is not maintained in Git.",
    REPOSITORY_NOT_REGISTERED: "The selected Repository is not registered in this Project.",
    REPOSITORY_NOT_PLANNING_VISIBLE: "The Repository is not planning-visible.",
    REPOSITORY_BRANCH_SELECTION_REQUIRED: "The checkout is detached; an explicit Repository branch is required.",
    INVALID_BRANCH_REF: "The base must be a valid local branch.",
    INVALID_TARGET_REF: "The target must be a valid local branch.",
    STALE_REPOSITORY_SELECTION_REVISION: "The Repository selection being revised is no longer current.",
    INVALID_REPOSITORY_SELECTION_CHANGE_REQUEST: "The Agent Repository selection change request is invalid.",
    SCOPE_EXPANSION_REQUIRED: "The plan requests Repository scope that is not authorized and needs human confirmation.",
    INCOMPLETE_REPOSITORY_SCOPE: "A plan must contain at least one Repository WorkUnit.",
    DUPLICATE_WORK_UNIT: "The plan contains a duplicate WorkUnit identifier.",
    DUPLICATE_STRING: "The list contains duplicate text.",
    DUPLICATE_REPOSITORY_WORK_UNIT: "A Repository can have only one WorkUnit in a plan.",
    MISSING_FROZEN_BASE: "The Repository has no frozen base suitable for execution.",
    WORK_UNIT_DEPENDENCY_CYCLE: "WorkUnit dependencies contain a cycle.",
    UNKNOWN_WORK_UNIT_DEPENDENCY: "A WorkUnit depends on an unknown WorkUnit.",
    COMBINED_VALIDATION_FAILED: "Combined validation did not pass for the exact Candidate set.",
    INITIAL_CONTEXT_BUDGET_EXCEEDED: "Initial context exceeds the 70 percent budget.",
    PROJECT_NOT_FOUND: "The requested Project was not found.",
    CHANGE_SET_NOT_FOUND: "The requested ChangeSet was not found.",
    PLAN_CONFIRMATION_REQUIRED: "The plan has not received human confirmation and cannot execute.",
    STALE_PLAN_CONFIRMATION: "The plan proposed for confirmation is no longer current.",
    STALE_BUNDLE_DECISION: "The Bundle proposed for review is no longer the exact current subject.",
    INVALID_CHANGE_SET_STATE: "The current ChangeSet state does not allow this operation.",
    INVALID_CHANGE_SET_CLOSURE: "The ChangeSet close request is missing fields, contains unknown fields, or exceeds its bounds.",
    CHANGE_SET_ABANDONED: "The ChangeSet is abandoned and cannot receive lifecycle mutations.",
    CHANGE_SET_NOT_QUIESCENT: "The ChangeSet still has a running Run or lifecycle command and cannot close.",
    CHANGE_SET_DELIVERY_STARTED: "The ChangeSet has begun delivery and cannot close.",
    CHANGE_SET_ALREADY_TERMINAL: "The ChangeSet is already terminal and cannot close again.",
    INCOMPLETE_CANDIDATE_SET: "Candidate results do not cover every WorkUnit in the current plan.",
    MISSING_REQUIRED_EVIDENCE: "Required immutable evidence is missing for Bundle assembly.",
    REPOSITORY_VALIDATION_FAILED: "Repository Candidate validation failed.",
    RUNTIME_IMPLEMENTATION_BLOCKED: "The Agent Runtime could not complete the implementation.",
    EMPTY_IMPLEMENTATION_RESULT: "The Agent Runtime produced no deliverable Git change.",
    EXECUTION_RETRY_SUBJECT_MISMATCH: "The retry workspace does not match the current exact WorkUnit.",
    EXECUTION_RETRY_HEAD_MOVED: "The retry workspace Git HEAD moved away from the confirmed base.",
    EXECUTION_RETRY_WORKSPACE_DIRTY: "The retry workspace contains partial changes and cannot be reset automatically.",
    COMMAND_SPAWN_FAILED: "The validation command could not be started.",
    CANDIDATE_CHECKPOINT_NOT_RESUMABLE: "The CandidateCheckpoint cannot currently resume validation.",
    CANDIDATE_CHECKPOINT_SUBJECT_MISMATCH: "The CandidateCheckpoint does not match the current exact WorkUnit.",
    CANDIDATE_CHECKPOINT_RUN_MISMATCH: "The CandidateCheckpoint source Run does not match.",
    CANDIDATE_CHECKPOINT_STATE_MISMATCH: "CandidateCheckpoint persistence state does not match.",
    LEGACY_RECOVERY_SUBJECT_MISMATCH: "The legacy recovery subject does not match the current exact WorkUnit.",
    LEGACY_RECOVERY_RUN_MISMATCH: "The legacy recovery source Run does not match.",
    STALE_PLAN_REVISION: "The specified plan is no longer the current confirmed revision.",
    IDEMPOTENCY_KEY_REUSED: "The same idempotency key cannot be used with different input.",
    LOCK_BUSY: "The control plane is currently owned by another executor.",
    NOT_A_GIT_REPOSITORY: "The specified path is not a Git repository.",
    DIRTY_CANDIDATE_WORKSPACE: "The Candidate workspace contains uncommitted changes.",
    CANDIDATE_HEAD_MISMATCH: "The Candidate workspace commit does not match the recorded Candidate.",
    CANDIDATE_REPOSITORY_MISMATCH: "The Candidate does not belong to the specified Repository.",
    CANDIDATE_CHANGED_PATHS_MISMATCH: "Candidate changed paths do not match the exact Git subject.",
    INVALID_GITHUB_DELIVERY_BINDING: "The GitHub delivery binding is invalid.",
    GITHUB_DELIVERY_BINDING_REQUIRED: "The Repository has no confirmed GitHub delivery binding.",
    GITHUB_DELIVERY_BINDING_NOT_FOUND: "The requested GitHub delivery binding revision was not found.",
    GITHUB_REMOTE_IDENTITY_MISMATCH: "The Git remote does not match the confirmed GitHub repository.",
    UNSUPPORTED_GITHUB_REMOTE: "The Git remote is not a supported GitHub URL.",
    INVALID_DELIVERY_REQUEST: "The delivery request identity is invalid.",
    DELIVERY_CANDIDATE_NOT_IN_BUNDLE: "The delivery Candidate is not part of the accepted Bundle.",
    DELIVERY_CANDIDATE_NOT_FOUND: "The exact delivery Candidate could not be found.",
    DELIVERY_EMPTY_CANDIDATE_UNSUPPORTED: "A no-change Candidate cannot create a GitHub pull request.",
    BUNDLE_ACCEPTANCE_REQUIRED: "The current exact Bundle is not accepted for delivery.",
    DELIVERY_NOT_PUBLISHED: "The current Bundle has no complete delivery request set.",
    DELIVERY_TARGET_MOVED: "The delivery target moved from the Candidate base.",
    DELIVERY_BRANCH_DIVERGED: "The delivery branch points at a different commit.",
    DELIVERY_RESULT_UNVERIFIED: "The exact GitHub merge result could not be verified.",
    INVALID_GITHUB_PULL_REQUEST: "The GitHub pull request response is invalid.",
    INVALID_GITHUB_PULL_REQUEST_TEXT: "The GitHub pull request text is invalid.",
    INVALID_GITHUB_RESPONSE: "GitHub returned an invalid response.",
    AMBIGUOUS_GITHUB_PULL_REQUEST: "More than one GitHub pull request matches the delivery branch.",
    GITHUB_PULL_REQUEST_NOT_FOUND: "The expected GitHub pull request was not found.",
    GITHUB_COMMAND_FAILED: "The GitHub command failed.",
    DELIVERY_GIT_PUSH_FAILED: "The exact Candidate could not be published to the Git remote.",
    GIT_REMOTE_READ_FAILED: "The Git remote target could not be read.",
    INVALID_DELIVERY_STATE: "The delivery state is invalid.",
    INVALID_DELIVERY_TARGET_REF: "The delivery target must be a branch ref.",
    INVALID_DELIVERY_BRANCH: "The ChangeFleet delivery branch name is invalid.",
    INVALID_COMMIT_SHA: "The Git commit identity is invalid.",
    AMBIGUOUS_GIT_REMOTE_REF: "The Git remote returned an ambiguous target ref.",
    INVALID_GIT_REMOTE_RESPONSE: "The Git remote returned an invalid ref.",
    GIT_DELIVERY_COMMAND_FAILED: "The Git delivery command could not be executed.",
    GIT_COMMIT_NOT_FOUND: "The requested Git commit was not found.",
    DELIVERY_RESULT_VERIFICATION_FAILED: "The delivery result could not be verified against Git.",
    DELIVERY_BUNDLE_NOT_FOUND: "The Bundle bound to delivery was not found.",
    DELIVERY_REQUEST_NOT_FOUND: "The requested delivery record was not found.",
    COMMAND_PREVIOUSLY_FAILED: "The same idempotent command previously failed.",
    COMMAND_STATE_MISMATCH: "The persisted command state does not match the current operation.",
  },
};

export function normalizeLocale(locale = DEFAULT_LOCALE) {
  return MESSAGES[locale] ? locale : "en";
}

export function diagnosticMessage(code, { locale = DEFAULT_LOCALE, fallback } = {}) {
  // 翻译缺失时使用调用边界提供的原始说明，未知语言确定性回退到英文目录。
  const resolvedLocale = normalizeLocale(locale);
  return MESSAGES[resolvedLocale][code] ?? fallback ?? `ChangeFleet 错误：${code}`;
}

// 边缘界面应调用此函数切换展示语言，而不是匹配或重写稳定错误码。
export function presentDiagnostic(error, locale = DEFAULT_LOCALE) {
  return {
    code: error.code ?? "UNEXPECTED_ERROR",
    message: diagnosticMessage(error.code ?? "UNEXPECTED_ERROR", { locale, fallback: error.message }),
    details: error.details,
    locale: normalizeLocale(locale),
  };
}
