// 此模块只翻译 ChangeFleet 自己定义的诊断；Git 和测试程序的原始输出必须保留为证据，不能擅自改写。
export const DEFAULT_LOCALE = "zh-CN";

const MESSAGES = {
  "zh-CN": {
    INVALID_AUDIT_QUERY: "审计查询参数无效。",
    AUDIT_SOURCE_NOT_FOUND: "未找到请求的审计源。",
    AUDIT_REQUIRED_REFERENCE_INVALID: "审计所需的不可变引用无效或缺失。",
    AUDIT_SOURCE_IDENTITY_MISMATCH: "审计源身份或内容摘要不匹配。",
    AMBIGUOUS_OBSERVATION_OVERLAP: "用量观察可能重叠，无法安全计算唯一总量。",
    INVALID_ID: "标识符格式无效。",
    INVALID_PLAN: "变更计划无效。",
    INVALID_PROJECT_REPOSITORIES: "项目必须显式登记至少一个仓库。",
    INVALID_REPOSITORY_SELECTION: "仓库选择无效。",
    INVALID_REPOSITORY_SELECTION_REVISION: "仓库选择版本无效。",
    INVALID_REPOSITORY_HARNESS_POLICY: "仓库 Harness 策略无效。",
    INVALID_REPOSITORY_HARNESS_SELECTION: "仓库 Harness 选择无效。",
    INVALID_REPOSITORY_HARNESS_SELECTION_REVISION: "仓库 Harness 选择版本无效。",
    STALE_REPOSITORY_HARNESS_SELECTION_REVISION: "待修订的仓库 Harness 选择已不是当前版本。",
    REPOSITORY_HARNESS_POLICY_REQUIRED: "启用本地 Harness overlay 前必须确认仓库策略。",
    REPOSITORY_HARNESS_POLICY_NOT_FOUND: "未找到指定的仓库 Harness 策略版本。",
    WORKTREEINCLUDE_NOT_TRACKED_AT_BASE: "所选基线没有受 Git 管理的 .worktreeinclude。",
    UNSAFE_HARNESS_PATH: "Harness 路径超出了允许的仓库边界。",
    UNSUPPORTED_HARNESS_RESOURCE: "所选文件不是允许的 Provider 语义 Harness 资源。",
    EMPTY_HARNESS_OVERLAY: "仓库 Harness 策略没有匹配到可用的忽略文件。",
    HARNESS_OVERLAY_LIMIT_EXCEEDED: "仓库 Harness overlay 超出了文件或字节限制。",
    HARNESS_OVERLAY_MODIFIED: "运行过程修改了冻结的 Harness overlay。",
    NON_GIT_HARNESS_CHANGE_UNSUPPORTED: "ChangeFleet 不支持交付未由 Git 管理的 Harness 修改。",
    REPOSITORY_NOT_REGISTERED: "所选仓库未登记在当前项目中。",
    REPOSITORY_NOT_PLANNING_VISIBLE: "仓库不在当前规划可见范围内。",
    REPOSITORY_BRANCH_SELECTION_REQUIRED: "检出点不在分支上，必须显式选择仓库分支。",
    INVALID_BRANCH_REF: "只能选择有效的本地分支作为基线。",
    INVALID_TARGET_REF: "只能选择有效的本地分支作为目标。",
    STALE_REPOSITORY_SELECTION_REVISION: "待修订的仓库选择已不是当前版本。",
    INVALID_REPOSITORY_SELECTION_CHANGE_REQUEST: "Agent 返回的仓库选择变更请求无效。",
    SCOPE_EXPANSION_REQUIRED: "计划请求了尚未授权的仓库范围，需要人工确认。",
    INCOMPLETE_REPOSITORY_SCOPE: "计划必须至少包含一个仓库工作单元。",
    DUPLICATE_WORK_UNIT: "计划中存在重复的工作单元标识符。",
    DUPLICATE_REPOSITORY_WORK_UNIT: "同一仓库在一个计划中只能有一个工作单元。",
    MISSING_FROZEN_BASE: "仓库没有可执行的冻结基线版本。",
    WORK_UNIT_DEPENDENCY_CYCLE: "工作单元依赖关系存在循环。",
    UNKNOWN_WORK_UNIT_DEPENDENCY: "工作单元依赖了不存在的工作单元。",
    COMBINED_VALIDATION_FAILED: "候选集合的联合验证未通过。",
    INITIAL_CONTEXT_BUDGET_EXCEEDED: "初始上下文超过允许的 70% 预算。",
    PROJECT_NOT_FOUND: "未找到指定项目。",
    CHANGE_SET_NOT_FOUND: "未找到指定变更单。",
    PLAN_CONFIRMATION_REQUIRED: "计划尚未经过人工确认，不能执行。",
    STALE_PLAN_CONFIRMATION: "待确认的计划已不是当前版本。",
    STALE_BUNDLE_DECISION: "待审核的候选包已不是当前精确版本。",
    INVALID_CHANGE_SET_STATE: "当前变更单状态不允许此操作。",
    INCOMPLETE_CANDIDATE_SET: "候选结果尚未覆盖当前计划的全部工作单元。",
    MISSING_REQUIRED_EVIDENCE: "缺少生成候选包所需的不可变证据。",
    REPOSITORY_VALIDATION_FAILED: "仓库候选结果未通过验证。",
    COMMAND_SPAWN_FAILED: "无法启动验证命令。",
    IDEMPOTENCY_KEY_REUSED: "同一个幂等键不能用于不同输入。",
    LOCK_BUSY: "控制面当前被另一个执行者占用。",
    NOT_A_GIT_REPOSITORY: "指定路径不是 Git 仓库。",
    DIRTY_CANDIDATE_WORKSPACE: "候选工作区含有未提交修改。",
    CANDIDATE_HEAD_MISMATCH: "候选工作区的 Git 提交与记录不一致。",
  },
  en: {
    INVALID_AUDIT_QUERY: "Audit query parameters are invalid.",
    AUDIT_SOURCE_NOT_FOUND: "The requested audit source was not found.",
    AUDIT_REQUIRED_REFERENCE_INVALID: "A required immutable audit reference is missing or invalid.",
    AUDIT_SOURCE_IDENTITY_MISMATCH: "Audit source identity or content digest does not match.",
    AMBIGUOUS_OBSERVATION_OVERLAP: "Usage observations may overlap, so one safe total cannot be derived.",
    INVALID_ID: "Identifier format is invalid.",
    INVALID_PLAN: "Change plan is invalid.",
    INVALID_PROJECT_REPOSITORIES: "A Project must explicitly register at least one Repository.",
    INVALID_REPOSITORY_SELECTION: "Repository selection is invalid.",
    INVALID_REPOSITORY_SELECTION_REVISION: "Repository selection revision is invalid.",
    INVALID_REPOSITORY_HARNESS_POLICY: "Repository Harness policy is invalid.",
    INVALID_REPOSITORY_HARNESS_SELECTION: "Repository Harness selection is invalid.",
    INVALID_REPOSITORY_HARNESS_SELECTION_REVISION: "Repository Harness selection revision is invalid.",
    STALE_REPOSITORY_HARNESS_SELECTION_REVISION: "The Repository Harness selection being revised is no longer current.",
    REPOSITORY_HARNESS_POLICY_REQUIRED: "A confirmed Repository policy is required before enabling a local Harness overlay.",
    REPOSITORY_HARNESS_POLICY_NOT_FOUND: "The requested Repository Harness policy revision was not found.",
    WORKTREEINCLUDE_NOT_TRACKED_AT_BASE: "The selected base has no tracked .worktreeinclude.",
    UNSAFE_HARNESS_PATH: "The Harness path exceeds the authorized Repository boundary.",
    UNSUPPORTED_HARNESS_RESOURCE: "The selected file is not an eligible Provider semantic Harness resource.",
    EMPTY_HARNESS_OVERLAY: "The Repository Harness policy matched no eligible ignored files.",
    HARNESS_OVERLAY_LIMIT_EXCEEDED: "The Repository Harness overlay exceeds its file or byte limits.",
    HARNESS_OVERLAY_MODIFIED: "The Run modified the frozen Harness overlay.",
    NON_GIT_HARNESS_CHANGE_UNSUPPORTED: "ChangeFleet cannot deliver a Harness change that is not maintained in Git.",
    REPOSITORY_NOT_REGISTERED: "The selected Repository is not registered in this Project.",
    REPOSITORY_NOT_PLANNING_VISIBLE: "The Repository is not planning-visible.",
    REPOSITORY_BRANCH_SELECTION_REQUIRED: "The checkout is detached; an explicit Repository branch is required.",
    INVALID_BRANCH_REF: "The base must be a valid local branch.",
    INVALID_TARGET_REF: "The target must be a valid local branch.",
    STALE_REPOSITORY_SELECTION_REVISION: "The Repository selection being revised is no longer current.",
    INVALID_REPOSITORY_SELECTION_CHANGE_REQUEST: "The Agent Repository selection change request is invalid.",
    SCOPE_EXPANSION_REQUIRED: "The plan requests Repository scope that is not authorized and needs human confirmation.",
    INCOMPLETE_REPOSITORY_SCOPE: "A plan must contain at least one Repository WorkUnit.",
    DUPLICATE_WORK_UNIT: "The plan contains a duplicate WorkUnit identifier.",
    DUPLICATE_REPOSITORY_WORK_UNIT: "A Repository can have only one WorkUnit in a plan.",
    MISSING_FROZEN_BASE: "The Repository has no frozen base suitable for execution.",
    WORK_UNIT_DEPENDENCY_CYCLE: "WorkUnit dependencies contain a cycle.",
    UNKNOWN_WORK_UNIT_DEPENDENCY: "A WorkUnit depends on an unknown WorkUnit.",
    COMBINED_VALIDATION_FAILED: "Combined validation did not pass for the exact Candidate set.",
    INITIAL_CONTEXT_BUDGET_EXCEEDED: "Initial context exceeds the 70 percent budget.",
    PROJECT_NOT_FOUND: "The requested Project was not found.",
    CHANGE_SET_NOT_FOUND: "The requested ChangeSet was not found.",
    PLAN_CONFIRMATION_REQUIRED: "The plan has not received human confirmation and cannot execute.",
    STALE_PLAN_CONFIRMATION: "The plan proposed for confirmation is no longer current.",
    STALE_BUNDLE_DECISION: "The Bundle proposed for review is no longer the exact current subject.",
    INVALID_CHANGE_SET_STATE: "The current ChangeSet state does not allow this operation.",
    INCOMPLETE_CANDIDATE_SET: "Candidate results do not cover every WorkUnit in the current plan.",
    MISSING_REQUIRED_EVIDENCE: "Required immutable evidence is missing for Bundle assembly.",
    REPOSITORY_VALIDATION_FAILED: "Repository Candidate validation failed.",
    COMMAND_SPAWN_FAILED: "The validation command could not be started.",
    IDEMPOTENCY_KEY_REUSED: "The same idempotency key cannot be used with different input.",
    LOCK_BUSY: "The control plane is currently owned by another executor.",
    NOT_A_GIT_REPOSITORY: "The specified path is not a Git repository.",
    DIRTY_CANDIDATE_WORKSPACE: "The Candidate workspace contains uncommitted changes.",
    CANDIDATE_HEAD_MISMATCH: "The Candidate workspace commit does not match the recorded Candidate.",
  },
};

export function normalizeLocale(locale = DEFAULT_LOCALE) {
  return MESSAGES[locale] ? locale : "en";
}

export function diagnosticMessage(code, { locale = DEFAULT_LOCALE, fallback } = {}) {
  // 翻译缺失时使用调用边界提供的原始说明，未知语言确定性回退到英文目录。
  const resolvedLocale = normalizeLocale(locale);
  return MESSAGES[resolvedLocale][code] ?? fallback ?? `ChangeFleet 错误：${code}`;
}

// 边缘界面应调用此函数切换展示语言，而不是匹配或重写稳定错误码。
export function presentDiagnostic(error, locale = DEFAULT_LOCALE) {
  return {
    code: error.code ?? "UNEXPECTED_ERROR",
    message: diagnosticMessage(error.code ?? "UNEXPECTED_ERROR", { locale, fallback: error.message }),
    details: error.details,
    locale: normalizeLocale(locale),
  };
}
